DELIMITER $$

CREATE TRIGGER RENTS_DELETE AFTER DELETE ON RENTS 
FOR EACH ROW
BEGIN
  INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID)
	VALUES (CURTIME(), "DELETE", OLD.RENT_ID);
END $$

DELIMITER ;
