DELIMITER $$

CREATE TRIGGER RENTS_UPDATE AFTER UPDATE ON RENTS 
FOR EACH ROW
BEGIN
  INSERT INTO RENTS_AUD (EVENT_DATE, EVENT_TYPE, RENT_ID, NEW_BOOK_ID, NEW_READER_ID, NEW_RENT_DATE, NEW_RETURN_DATE, 
						OLD_BOOK_ID, OLD_READER_ID, OLD_RENT_DATE, OLD_RETURN_DATE)
	VALUES (CURTIME(), "UPDATE", OLD.RENT_ID, NEW.BOOK_ID, NEW.READER_ID, NEW.RENT_DATE, NEW.RETURN_DATE,
						OLD.BOOK_ID, OLD.READER_ID, OLD.RENT_DATE, OLD.RETURN_DATE);
END $$

DELIMITER ;