INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
	VALUES (1, 3, CURDATE() - 5, NULL);
    
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
	VALUES (2, 3, CURDATE() - 2, NULL);
    
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
	VALUES (3, 1, CURDATE() - 9, NULL);
    
INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
	VALUES (2, 4, CURDATE() - 3, NULL);
    
COMMIT;