DROP FUNCTION IF EXISTS UpdateBestseller;

DELIMITER $$ 

CREATE FUNCTION UpdateBestseller(timesrented DECIMAL(5,2)) RETURNS BOOLEAN DETERMINISTIC
BEGIN
	DECLARE result BOOLEAN DEFAULT FALSE;
	IF timesrented >= 0,66 THEN
		SET result = TRUE;	
	END IF;
    RETURN result;
END $$

DELIMITER ;

-- SELECT UpdateBestseller(2) AS STATUS;