DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
	DECLARE TIMESRENT, BK_ID INT;
    DECLARE RENTSPERMONTH DECIMAL(5,2);
	DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
		FETCH ALL_BOOKS INTO BK_ID;
        IF (FINISHED = 0) THEN
			SELECT COUNT(*) FROM RENTS
			 WHERE BOOK_ID = BK_ID
			  INTO TIMESRENT;			
			SET RENTSPERMONTH = TIMESRENT / 30;
			UPDATE BOOKS SET BESTSELLER = UpdateBestseller(RENTSPERMONTH)
            WHERE BOOK_ID = BK_ID;
			COMMIT;
		END IF;
	END WHILE;
    CLOSE ALL_BOOKS;    
END $$

DELIMITER ;
